In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv


In [2]:
df = pd.read_csv("/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv")
df = df.sample(n=20000)
df.shape

(20000, 2)

In [3]:
df.head()

review sentiment
18919  I remember seeing this film in the theater and...  positive
41307  Very good point there : "only an elite few (th...  positive
32763  This movie is really bad. The hero can't play....  negative
17716  Unlike what one reviewer said this is NOT a ri...  negative
10385  If I could give this movie less than a 1, I wo...  negative

In [4]:
# Overviewing out sample data
df['review'].iloc[0]

'I remember seeing this film in the theater and liking it. I happened to stumble upon it on fear net last month and watched it again and found it better with age. First of all for those of you who describe this as 80s cheese if you objectively compare it with the horror flicks of the past 2 decades it compares quite well if stacked up against films in its unique horror sub genre which I would term action/horror as opposed to psychological horror such as "The Shining" or "the exorcist".<br /><br />Furthermore for its budget this film really delivers the goods (or in this instance bad). The film actually has some character development and gives enough of a history of the infamous hull house to get the atmosphere right before the characters set foot in the front door. The film also has several hilarious one liners and gives the appropriate mood that a creepy horror flick should have. If you compare NOD to contemporary big budget horror films such as "I am legend" (The Vincent Price versio

In [5]:
# removing the Html tags
import re

def remove_html_tags(text):
  clean = re.compile('<.*?>')
  return re.sub(clean, '', text)

remove_html_tags(df['review'].iloc[0])

# The code seems to work properly

'I remember seeing this film in the theater and liking it. I happened to stumble upon it on fear net last month and watched it again and found it better with age. First of all for those of you who describe this as 80s cheese if you objectively compare it with the horror flicks of the past 2 decades it compares quite well if stacked up against films in its unique horror sub genre which I would term action/horror as opposed to psychological horror such as "The Shining" or "the exorcist".Furthermore for its budget this film really delivers the goods (or in this instance bad). The film actually has some character development and gives enough of a history of the infamous hull house to get the atmosphere right before the characters set foot in the front door. The film also has several hilarious one liners and gives the appropriate mood that a creepy horror flick should have. If you compare NOD to contemporary big budget horror films such as "I am legend" (The Vincent Price version was much b

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20000 entries, 18919 to 39611
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   review     20000 non-null  object
 1   sentiment  20000 non-null  object
dtypes: object(2)
memory usage: 468.8+ KB


In [7]:
df['review'] = df['review'].apply(remove_html_tags)

In [8]:
# Conveting the text to lowarcase
def Lower(text:str)->str:
    return text.lower()

Lower(df['review'].iloc[0])
# The code seems to work properly

'i remember seeing this film in the theater and liking it. i happened to stumble upon it on fear net last month and watched it again and found it better with age. first of all for those of you who describe this as 80s cheese if you objectively compare it with the horror flicks of the past 2 decades it compares quite well if stacked up against films in its unique horror sub genre which i would term action/horror as opposed to psychological horror such as "the shining" or "the exorcist".furthermore for its budget this film really delivers the goods (or in this instance bad). the film actually has some character development and gives enough of a history of the infamous hull house to get the atmosphere right before the characters set foot in the front door. the film also has several hilarious one liners and gives the appropriate mood that a creepy horror flick should have. if you compare nod to contemporary big budget horror films such as "i am legend" (the vincent price version was much b

In [9]:
# Now applying it to the all rows
df['review'] = df['review'].apply(Lower)

In [10]:
# removing the alphanumeric characters
def remove_special(text):
    x = ''
    for i in text:
        if i.isalnum():
            x = x+i
        else:
            x = x + ' '
    return x

In [11]:
# Now applying this to the whole column
df['review'] = df['review'].apply(remove_special)

In [12]:
# Removal of the stopwords
import nltk
from nltk.corpus import stopwords

# Download the stopwords list
nltk.download('stopwords')

def remove_stopwords(text:str)->str:
    stop_words = set(stopwords.words('english'))
    filtered_words = [word for word in text.split() if word.lower() not in stop_words]
    return ' '.join(filtered_words)

[nltk_data] Downloading package stopwords to /usr/share/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [13]:
# Apply the above function to the column
df['review'] = df['review'].apply(remove_stopwords)

In [14]:
df['review'].iloc[0]
# The above code seems to work properly

'remember seeing film theater liking happened stumble upon fear net last month watched found better age first describe 80s cheese objectively compare horror flicks past 2 decades compares quite well stacked films unique horror sub genre would term action horror opposed psychological horror shining exorcist furthermore budget film really delivers goods instance bad film actually character development gives enough history infamous hull house get atmosphere right characters set foot front door film also several hilarious one liners gives appropriate mood creepy horror flick compare nod contemporary big budget horror films legend vincent price version much better film really stands modern horror flicks become almost completely dominated cgi plot character devel completely predictable special effects dominate movies start finish characters 24k plastic 80s horror cheese take 95 current entries genre closing note seeing nod made remember beautiful jill terashita wonder seen films horror other

In [15]:
# now applying the stemming
from nltk.stem import PorterStemmer

# Download NLTK data (if not already downloaded)
nltk.download('punkt')

def stemm(text:str)->str:
    stemmer = PorterStemmer()
    stemmed_words = [stemmer.stem(word) for word in text.split()]
    return ' '.join(stemmed_words)

[nltk_data] Downloading package punkt to /usr/share/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [16]:
# Appling the stemm function to the review column
df['review'] = df['review'].apply(stemm)

In [17]:
df['review'].iloc[0] # The code seems to be working properly

'rememb see film theater like happen stumbl upon fear net last month watch found better age first describ 80 chees object compar horror flick past 2 decad compar quit well stack film uniqu horror sub genr would term action horror oppos psycholog horror shine exorcist furthermor budget film realli deliv good instanc bad film actual charact develop give enough histori infam hull hous get atmospher right charact set foot front door film also sever hilari one liner give appropri mood creepi horror flick compar nod contemporari big budget horror film legend vincent price version much better film realli stand modern horror flick becom almost complet domin cgi plot charact devel complet predict special effect domin movi start finish charact 24k plastic 80 horror chees take 95 current entri genr close note see nod made rememb beauti jill terashita wonder seen film horror otherwis jill odd chanc read think gorgeou film lastli like action horror flick probabl like one lot'

In [18]:
# Converting sentiment column to 0's and 1's
# 1 for positive review and 0 for the negative review
def convert(word):
    if(word=='positive'):
        return 1
    return 0;
convert(df['sentiment'].iloc[0])
# The above code seems to be working properly

1

In [19]:
df['sentiment'] = df['sentiment'].apply(convert)

In [20]:
df
# Now our data is much more preprocessed
# Now we can move forward by applying bag of words technique

review  sentiment
18919  rememb see film theater like happen stumbl upo...          1
41307  good point elit upper class would access inter...          1
32763  movi realli bad hero play see much learn walk ...          0
17716  unlik one review said ripoff magnum forc one l...          0
10385  could give movi less 1 would certainli read re...          0
...                                                  ...        ...
45273  guess reward idioci today whoever came concept...          0
8793   movi realli surpris doubt first movi got bette...          1
14173  movi purport show middl class famili attempt f...          0
10031  everyon told see cactu flower final wonder mov...          1
39611  disappoint movi familiar case read mark fuhrma...          0

[20000 rows x 2 columns]

In [21]:
from sklearn.feature_extraction.text import CountVectorizer

vectoriser = CountVectorizer()

In [22]:
X = vectoriser.fit_transform(df['review']).toarray() # This is our feature
print(X[0:5])
print("Shape of X is : ", X.shape)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Shape of X is :  (20000, 48939)


In [23]:
y = df['sentiment'].values
print(y[0:5])
print("The shape of y is : ",y.shape)

[1 1 0 0 0]
The shape of y is :  (20000,)


In [24]:
# Creating training and test dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.1, random_state=42)

In [25]:
X_train.shape

(18000, 48939)

In [26]:
X_test.shape

(2000, 48939)

In [27]:
# Importing models from the sklearn library
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
clf1 = GaussianNB()
clf2 = MultinomialNB()
clf3 = BernoulliNB()

# Fitting the models
clf1.fit(X_train, y_train)
clf2.fit(X_train, y_train)
clf3.fit(X_train, y_train)

print('Model Training compleat')

Model Training compleat


In [28]:
# now let's make some predictions
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)
y_pred3 = clf3.predict(X_test)

In [29]:
# Now lets calculate the individual accuracies
from sklearn.metrics import accuracy_score
print("Accuracy Score for GaussianNB : ", accuracy_score(y_test, y_pred1))
print("Accuracy Score for MultinomialNB : ", accuracy_score(y_test, y_pred2))
print("Accuracy Score for BernoulliNB : ", accuracy_score(y_test, y_pred3))

Accuracy Score for GaussianNB :  0.6245
Accuracy Score for MultinomialNB :  0.8225
Accuracy Score for BernoulliNB :  0.8165
